### ISSUE TITLE
TMU map has unsecure links to tiles

### ISSUE THREAD

**Issue by Sim00n** [VATUSA/current#11]
Hey, I apologize if there are instructions somewhere on how to contribute/report issues, but I haven't found any.

I'm embedding the TMU map on my ARTCC's site and it's causing loading mixed content issues because the tiles are not loaded via HTTPS.

https://github.com/VATUSA/current/blob/610eeeb0b98a69d972cc0a41af29d98ae30c8184/resources/views/tmu/tmu.blade.php#L95

current/resources/views/tmu/tmu.blade.php line 95, 97 and perhaps 99

Cheers

**Comment by bnahin** [comment]
Fixed, thank you.
