### ISSUE TITLE
[BUG] Error when attempting to view training record

### ISSUE THREAD

**Issue by blindsey01** [VATUSA/current#45]
### Contact Details

datm@zlcartcc.com

### What happened?

When attempting to view a training record for a student written by an instructor with a deleted account, an Internal Server Error is returned. The training record cannot be accessed.

### How can it be reproduced?

1. View training records for 1455975
2. Attempt to view any training record created by instructor 'Account Erased'
3. Error is returned after a brief delay

### What browsers are you seeing the problem on?

Firefox, Chrome

### Screenshots

http://prntscr.com/1lxj655 - training record
http://prntscr.com/1lxjqy6 - error

**Comment by bnahin** [comment]
Fixed in api repository.
