### ISSUE TITLE
Allow mentors to access trainee's exam results

### ISSUE THREAD

**Issue by erikquinn** [VATUSA/current#46]
### Contact Details

ta@zmaartcc.net

### Is your feature request related to a problem? If so, please describe.

Currently, only instructors have access to exam results. My mentors go over exam results with the trainee during the first session on a new position. However, _they do not have access to view the exam results on the VATUSA website_, only instructors do.

My workaround is that I have to manually copy and paste the results and all missed exam questions from the VATUSA website into our local ZMA system so the mentors are able to see and review the missed exam questions with the trainee. Obviously, it gets a bit old doing this 😜 

### What is your new feature idea or request?

I know it was decided a while ago to give mentors this access (or grant a TA the option to toggle exam access for mentors), and that is my feature request. Give mentors the ability to see exam results. For those concerned about cheating, the below are possible resolutions to that:
- only allow viewing of exams they have passed themselves, or
- allow senior staff to toggle "Can view exam results" for any mentor

**Comment by bnahin** [comment]
This will be a feature of the upcoming VATUSA Academy by assigning the Mentor role to the Quiz object. More information about this will come later. No new features will be developed for the old Exam Center to encourage moving to the new Academy.
