### ISSUE TITLE
Training Records and OTS Records no longer available for a controller upon ARTCC Xfer

### ISSUE THREAD

**Issue by bengustafson84** [VATUSA/current#47]
### Contact Details

beng@denartcc.org

### What is your new feature idea or request?

Training records and OTS Records from a facility are no longer available when a controller transfers to another ARTCC.

These training records and OTS records should always be accessible from the facility in which they are generated from, regardless of the student/controller's current ARTCC.

**Comment by bnahin** [comment]
#49 Merged.
