### ISSUE TITLE
All training records showing Instructor as "Account Erased"

### ISSUE THREAD

**Issue by erikquinn** [VATUSA/current#48]
### Contact Details

ta@zmaartcc.net

### What happened?

A recent update appears to have caused all training records to show the "Instructor" for that record as "Account Erased". The correct instructor names were previously present, and appear properly in the Training Statistics view. It is only when opening the record itself to view it that the incorrect information is shown.

### How can it be reproduced?

Open any training record and view the specified instructor.

The example in the screenshot can be viewed at the link below; see 8/2/21:
https://www.vatusa.net/mgt/controller/1305373#training

### What browsers are you seeing the problem on?

Google Chrome, Version 92.0.4515.131 (Official Build) (64-bit)

### Screenshots

![image](https://user-images.githubusercontent.com/5103735/129283019-984cc6e8-f030-4846-b5e9-13919a1999a0.png)

**Comment by bnahin** [comment]
Oops.
