### ISSUE TITLE
[BUG] NTOS Posting Error

### ISSUE THREAD

**Issue by ml0130** [VATUSA/current#60]
### Contact Details

mlarosh@zhuartcc.org

### What happened?

NTOS throwing an error on TMI posting regarding Preferred Routing. I have tried both with normal and urgent priority

### How can it be reproduced?

On my end, I was able to get the error to come up more than once. But don't know if it will show for anyone else.

### What browsers are you seeing the problem on?

Chrome

### Screenshots

![image](https://user-images.githubusercontent.com/27445711/134999559-01bc0954-e9c5-4d08-b5d5-6be6e30b9fe4.png)

![image](https://user-images.githubusercontent.com/27445711/134999527-459fc6a8-1c26-46a9-8606-4c1b0ba1bcca.png)

**Comment by bnahin** [comment]
Please reproduce the problem so that our exception tracker can log the error.
