### ISSUE TITLE
[BUG] Loading the 'Facility Management' page takes 2minutes+ or times out

### ISSUE THREAD

**Issue by kmoberg** [VATUSA/current#64]
### Contact Details

atm@nyartcc.org

### What happened?

For quite some time now (over a month) we (myself, Gizep and Reed) are unable to open the facility management page of the VATUSA website, in less than 2-3 minutes per click. Most of the time it ends up timing out instead. If we're lucky enough to actually be able to load the page, every time we perform an action, we're redirected back to the front 'facility management' page, which again takes multiple minutes to load.

In reality, this makes the VATUSA website impossible to use for us, and results in significant delays to transfers being accepted etc. because we can't be assed to wait for that long.

### How can it be reproduced?

Login as myself, Gizep or Reed, and click the 'facility management' button.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Screenshots

http://kmoberg.io/sDn68i

**Comment by bnahin** [comment]
It is most likely the result of the synchronous processing of the training records table. Will need to change to be asynchronous.

**Comment by bnahin** [comment]
While these optimizations are taking place, are there any other pages that take an excessive time to load?
