### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TechFlyGuy** [VATUSA/current#67]
### Contact Details

datm@zfwartcc.net

### What happened?

While reading over the welcome to ZFW email, it is sending an outdated email from a previous ATM. It is not sending the one from the VATUSA website.

### How can it be reproduced?

1) User selects ZFW ARTCC
2) Automatically accepted or manually accepted
3) Old email generated

### What browsers are you seeing the problem on?

Chrome

### Screenshots

Old email being sent: https://prnt.sc/20xdwzp

New email template:
1) https://prnt.sc/20xdxsb
2) https://prnt.sc/20xdxwx
3) https://prnt.sc/20xdy1o

**Comment by bnahin** [comment]
The attached email address did not originate from VATUSA. This is evident because of the following:
1. Email template.
2. Subject.
3. Email from Name.
This is not a bug with VATUSA.
