### ISSUE TITLE
[FEAT] Training records available regardless of roster status

### ISSUE THREAD

**Issue by MegBruck** [VATUSA/current#74]
### Contact Details

m.bruck@vatusa.net

### What is your new feature idea or request?

Currently, student training records are only visible to senior staff if the student is on the home or visiting roster. A request from the TAs (approved by USA1) has been made to remove this restriction and allow the student training records to be viewable by senior staff regardless of home or visitor status.

**Comment by Jonhasacat** [comment]
Implemented in #77
