### ISSUE TITLE
[BUG] Facility Staff Members Still Unable to View Training Statistics of Other Facilities

### ISSUE THREAD

**Issue by blindsey01** [VATUSA/current#82]
### What happened?

When you go to the training statistics page and attempt to select another facility from the dropdown menu, you are redirected back to your own facilities statistics.

### How can it be reproduced?

1. Open browser of choice
2. VATUSA website -> Facility Management -> Training
3. Select facility other than own in dropdown menu
4. Wait to see your own facilities training stats again

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by arobison203** [comment]
Looks like this is fixed by #80 which just got merged in.
