### ISSUE TITLE
Allow SMT to execute moderation MEE6 commands [FEAT] 

### ISSUE THREAD

**Issue by Sramire** [VATUSA/current#90]
### Contact Details

simonthefilmmaker@outlook.com

### What is your new feature idea or request?

Add to the / or ! Commands available to the SMT. Ideally the !clear command to be able to mass delete messages (after being logged) due to being inappropriate, off topic or etc..

**Comment by Jonhasacat** [comment]
This request is obsolete with the announcement of the Discord Moderation Team.
